### ISSUE TITLE
Model is removed from OpenAI

### ISSUE THREAD

**Issue by D3FAU4T** [PawanOsman/ChatGPT-Official#1]
`text-chat-davinci-002-20230126` model was removed from OpenAI API and it no longer works. All github repos using this model getting the same 404 error "Model doesn't exist".

**Comment by proudparrot2** [comment]
Yeah I'm getting that also

**Comment by PawanOsman** [comment]
You can use this, this uses the new model founded
I do not share the model name to prevent OpenAI remove it soon

https://gist.github.com/PawanOsman/be803be44caed2449927860956b240ad

**Comment by D3FAU4T** [comment]
Thanks for helping! I was using it for my discord bot and it suddenly stopped working.

**Comment by D3FAU4T** [comment]
I've a question. Can it remember context or do I have to handle that on my end?

**Comment by 0xdevalias** [comment]
> You can use this, this uses the new model founded
> I do not share the model name to prevent OpenAI remove it soon

And how do we know this service won't just log/steal our API tokens?

**Comment by PawanOsman** [comment]
> > You can use this, this uses the new model founded
> > I do not share the model name to prevent OpenAI remove it soon
> 
> And how do we know this service won't just log/steal our API tokens?

Its up to you, i don't force anyone use my services, i have many free services and its 2 - 3 months i launched a bypass server for ChatGPT which many peoples using it and puting thier tokens on it

You can ask them, they all know that i don't need any key or token

Its not something i can prove for you you can join the discord server and ask them,

or you can just use my other API which uses my own API Key and you dont need to put your key
I shared as a repository named "ChatGPT"
