### ISSUE TITLE
Error overloaded

### ISSUE THREAD

**Issue by jo-project** [PawanOsman/ChatGPT-Official#5]
Error: That model is currently overloaded with other requests. You can retry your request, or contact us through our help center at help.openai.com if the error persists.

How to fix this?

**Comment by oiisamiio** [comment]
Get an OpenAI Pro Account + Pro API Key or wait...

**Comment by lslzl3000** [comment]
The default free model is shared by everyone around world, OpenAI has set a limit number to that model, so you have to wait or buy a paid model
