### ISSUE TITLE
The response has no identifier for code content?

### ISSUE THREAD

**Issue by lslzl3000** [PawanOsman/ChatGPT-Official#6]
The api return plain text for all content, which is fine for most of cases.
But for code, is there any identifier to mark code content?  

like markdown style  start with ```
e.g. current res:
> You: give me a js sort example
> ChatGPT: 
> 
> Here is an example of a JavaScript sort function: 
> 
> function sortArray(arr) { 
>   arr.sort(function(a, b) { 
>     return a - b; 
>   }); 
> }

It should be mark with ```:

> ChatGPT: 
> Here is an example of a JavaScript sort function: 
> 
> ```
> Here is an example of a JavaScript sort function: 
> 
> function sortArray(arr) { 
>   arr.sort(function(a, b) { 
>     return a - b; 
>   }); 
> }
> ```

Does OpenAI not provide any relevant identifier or filtered on the node module side?

**Comment by PawanOsman** [comment]
the response is markdown and its returned by OpenAI, nothing changed by this Package
