### ISSUE TITLE
it's not using ChatGPT Plus subscription - instead billing my OpenAI account

### ISSUE THREAD

**Issue by 7flash** [PawanOsman/ChatGPT-Official#7]
https://github.com/PawanOsman/ChatGPT-Official/blob/09f8ade97c21cbc74db07af1ae5b6c3ada078586/src/classes/chatgpt.ts#L174

**Comment by PawanOsman** [comment]
this package is for creating ChatGPT using the official OpenAI API, it's not using ChatGPT account
